### ISSUE TITLE
Fix README file

### ISSUE THREAD

**Issue by nirgn975** [DavidBronfen/Retrogusto#2]
Couple of the sections header are `h1` (`#`) and they should be `h2` (`##`):

<img width="345" alt="https___raw_githubusercontent_com_davidbronfen_retrogusto_master_readme_md" src="https://cloud.githubusercontent.com/assets/3472902/23071504/37ca36c6-f537-11e6-9005-e09308b45ac3.png">

**Comment by DavidBronfen** [comment]
@nirgn975 Do i need to add those headers? 
or just to modify mine to be `h2`?

**Comment by nirgn975** [comment]
@DavidBronfen You can close this Issue, since the PR was merged.
