### ISSUE TITLE
Get all the recipes belong to the given category

### ISSUE THREAD

**Issue by DavidBronfen** [DavidBronfen/Retrogusto#33]
- [x] Create a service that brings all the recipes that belong to the given category.
- [x] Create action. 
- [ ] Despatch that action. 
- [x] Create effect (that can catch the despatched action).
  - [ ] This effect action will use the categories service and will despatch it to the success action.
- [ ] Create reducer (that can catch the despatched action).

Based on: #28 and #27

**Comment by nirgn975** [comment]
And remove Node.js 7 from `.travis.yml`.

**Comment by nirgn975** [comment]
Also, master branch is failed because `target` is still on 60% in codecov. Are you sure you changed it?

**Comment by DavidBronfen** [comment]
@nirgn975 This screenshot is taken an hour ago:

<img width="259" alt="team_yaml" src="https://user-images.githubusercontent.com/12427216/28211685-95832664-68a6-11e7-8b78-0c89cd0b6737.png">
